JY-13: JSON 객체 파싱하기
DONOTINTO/IOSProjects pull request #17
Opened 2023-04-14 09:01 UTC by DONOTINTO

- 카드번호 : [JY-13](https://keentutoring.atlassian.net/browse/JY-13) 
  - 네트워크 통신을 통해 가져온 Data를 커스텀 모델 객체로 변환합니다.

2023-04-14 09:34 UTC, keenkim1202 requested changes
확인 후 수정해주세요~!

2023-04-14 09:34 UTC, keenkim1202 commented on APIPractice/APIPractice/Beer.swift
> +//name, tagline, first_brewed, description, image_url, abv
불필요한 코멘트 제거해주세요

2023-04-14 09:34 UTC, keenkim1202 commented on APIPractice/APIPractice/ViewController.swift
> +    //https://api.punkapi.com/v2/beers/random
불필요한 코멘트 제거해주세요

2023-04-14 09:34 UTC, keenkim1202 commented on APIPractice/APIPractice/ViewController.swift
> +    @IBAction func resetButtonClicked(_ sender: Any) {
action 함수가 클래스 가장 하단에 위치하도록 배치해주세요~!
(fetch함수가 불리는 곳보다 상단에 정의 되어 있어야함)

2023-04-14 09:34 UTC, keenkim1202 commented on APIPractice/APIPractice/ViewController.swift
> +            print("response status : \(response.statusCode)")
불필요한 프린트문은 제거해주세요

2023-04-15 05:04 UTC, DONOTINTO commented on APIPractice/APIPractice/ViewController.swift
> +            print("response status : \(response.statusCode)")
@keenkim1202 전부 수정완료했습니다!

2023-04-15 05:06 UTC, keenkim1202 approved these changes

2023-04-15 05:07 UTC, merged