[Update] 기본 정렬 및 체크에 따른 정렬 구현
DONOTINTO/IOSProjects pull request #5
Opened 2023-03-06 13:15 UTC by DONOTINTO

2023-03-07 03:40 UTC, keenkim1202 requested changes

2023-03-07 03:40 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +        // filter -> 체크 / 미체크 분리
불필요한 주석은 제거해주세요!
만약 주석을 남겨두고 싶다면 아래왁 같이 작성해주세요.
```suggestion
        // filter를 사용하여 체크 / 미체크 분리하여 정렬 후 합쳐서 리턴
        func highToLow() { ...
```

2023-03-07 03:40 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +        print("오름차순")
print() 문 제거해주세요!

2023-03-07 10:32 UTC, DONOTINTO commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +        print("오름차순")
@keenkim1202 완료!

2023-03-07 10:32 UTC, DONOTINTO commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +        // filter -> 체크 / 미체크 분리
@keenkim1202 완료!

2023-03-07 15:13 UTC, keenkim1202 requested changes

2023-03-07 15:13 UTC, keenkim1202 commented on ShoppingList/ShoppingList/CheckButton.swift
> +class CheckButton: UIButton {
@DONOTINTO 
CheckButton을 만든 이유와 역할은 무엇인가요?

2023-03-07 15:13 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +//        let checkedList = shoppingList.filter { $0.check }.sorted { $0.name > $1.name }
@DONOTINTO 
위의 주석과 Tab 간격을 맞춰주세요!

2023-03-07 15:13 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +//        let checkedList = shoppingList.filter { $0.check }.sorted { $0.name > $1.name }
만약 불필요하다면 삭제해주세요~!

2023-03-07 15:13 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ViewController.swift
> +    var itemSection: Int?
아래의 `itemIndex`에는 row, `itemSection`에는 section 값이 들어가는 것으로 보여집니다.
그렇다면 이름을 일관성있게 `itemRow`, `itemSection` 으로 짓거나 Tuple 형태로 하나의 묶음으로 값을 받는게 어떨까요?

2023-03-07 15:13 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ViewController.swift
> +            ShoppingManager.shared.update(name: name, section: itemSection!, index: itemIndex!)
`nil` 일 가능성이 있는 상황에서는 항상 optional binding을 사용하도록 합니다
강제 언랩핑의 사용은 지양하는게 어떨까요?

2023-03-07 15:13 UTC, keenkim1202 commented on ShoppingList/ShoppingList/ViewController.swift
> +        let item = ShoppingManager.shared.getShoppingItem(section: indexPath.section, index: indexPath.row)
section과 row 정보 둘다 인자로 받고자 한다면, 이름을 좀더 명시적으로 아래와 같이 바꿔주는게 좋습니다.
index라는 단어는 section과 row를 모두 포함하고 있는 단어입니다!
```suggestion
        let item = ShoppingManager.shared.getShoppingItem(section: indexPath.section, row: indexPath.row)
```

2023-03-08 14:09 UTC, DONOTINTO commented on ShoppingList/ShoppingList/CheckButton.swift
> +class CheckButton: UIButton {
@keenkim1202 섹션 구분에 필요한 section과 row값을 저장하고 싶었는데, 이전에 알려줬던 tag로는 하나의 값밖에 저장이 안돼서 그냥 class를 만들었습니다.
extention으로 property를 추가할까도 했지만 stored property는 만들지 못한다고 해서 클래스로 만들었습니다

2023-03-08 14:09 UTC, DONOTINTO commented on ShoppingList/ShoppingList/ShoppingManager.swift
> +//        let checkedList = shoppingList.filter { $0.check }.sorted { $0.name > $1.name }
@keenkim1202 수정 완료했습니다!

2023-03-08 14:09 UTC, DONOTINTO commented on ShoppingList/ShoppingList/ViewController.swift
> +    var itemSection: Int?
@keenkim1202 수정 완료했습니다!

2023-03-08 14:09 UTC, DONOTINTO commented on ShoppingList/ShoppingList/ViewController.swift
> +        let item = ShoppingManager.shared.getShoppingItem(section: indexPath.section, index: indexPath.row)
@keenkim1202 수정 완료했습니다!

2023-03-08 15:38 UTC, keenkim1202 approved these changes

2023-03-08 15:41 UTC, keenkim1202 commented
@DONOTINTO 
컨벤션도 완벽하고 코드도 잘 수정해주셨습니다. 머지하겠습니다~! 👍

2023-03-08 15:41 UTC, merged