[Update] 김/이/박/최/기타 섹션 구분
DONOTINTO/IOSProjects pull request #6
Opened 2023-03-06 13:16 UTC by DONOTINTO

2023-03-06 13:18 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        switch firstName {
@keenkim1202 이렇게 switch문으로 해결하는 방법말고 좀 더 아름다운 방식이 없을까용
나중에 분기가 막 100개 이렇게 됐을 때도 이렇게 하나하나 해줘야하는지가 고민입니다..

2023-03-07 03:42 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        switch firstName {
@DONOTINTO 
배열을 만들어주는 방법이 있습니다~!
```swift
var sectionList: [String] = ["섹션1", "섹션2"] // 섹션 title 목록이 들어있는 배열 생성

func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
    return sectionList[section]
}
```

2023-03-07 03:48 UTC, keenkim1202 requested changes

2023-03-07 03:48 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/StudentManager.swift
> +        case "김": StudentManager.shared.kimList.append(fullName); break
break는 꼭 안해줘도 됩니다.
```suggestion
        case "김": StudentManager.shared.kimList.append(fullName)
```

2023-03-07 03:48 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +    case kim = 0
이미 알고있을 수도 있지만 작성해둡니다ㅎㅎ
rawValue를 Int 타입으로 지정해줄 때, 첫번째 case를 0 부터 시작할 거라면 대입해주지 않아도 됩니다!
```suggestion
    case kim
```

2023-03-07 03:48 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        case .none: return nil
김이박최에 속하지 않는 사람은 "기타" 섹션에 담아주세요~!

```suggestion
        default: return "기타"
```

2023-03-07 03:48 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        case .none: return 0
`case .none` 은 잘 사용하지 않습니다.
`firstName`에 들어올 수 있는 `case`들을 제외한 나머지 `case`를 의미하고자 한다면 `default`를 사용해주세요

2023-03-07 03:48 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        case .none: break
여기도 마찬가지 입니다!

2023-03-07 05:16 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/StudentManager.swift
> +        case "김": StudentManager.shared.kimList.append(fullName); break
수정 완료했습니다!

2023-03-07 05:17 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        switch firstName {
@keenkim1202 수정 완료했습니다!

2023-03-07 05:18 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +    case kim = 0
수정 완료했습니다!

2023-03-07 05:18 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        case .none: return nil
수정 완료했습니다!

2023-03-07 05:18 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        case .none: return 0
넵! 수정 완료했습니다!

2023-03-07 05:18 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        case .none: break
수정 완료했습니다!

2023-03-07 15:16 UTC, keenkim1202 requested changes

2023-03-07 15:16 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        StudentManager.shared.testAppend(firstName: String(studentFirstName), fullName: studentName)
`studentFirstName`을 `String` 타입으로 캐스팅을 하려고 한다면 
위의 `guard let` 구문에서 진행하는 것이 좋을 것 같습니다~!

2023-03-07 15:16 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/ViewController.swift
> +        print(StudentManager.shared.nameList)
불필요하다면 삭제해주세요!
(항상 push 하기전에 불필요한 print문이 포함되어있는지 체크해주세요)

2023-03-07 15:18 UTC, keenkim1202 commented
@DONOTINTO 
첫번째 수정사항들 모두 잘 수정되었습니다!
추가적인 수정사항이 있으니 확인 후 수정하여 다시 리뷰를 요청해주세요~!
(오른쪽 상단 Reviewers 부분에 닉네임 옆 recycle 화살표 모양 클릭)

2023-03-08 15:45 UTC, keenkim1202 requested changes

2023-03-08 15:45 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/StudentManager.swift
> +        var firstNameExist = false
@DONOTINTO 
Bool 타입 변수명을 지을 때는 앞에 prefix로 has, is 와 같은 단어들을 많이 붙입니다.
Swift에서 적용하고 있는 네이밍 컨벤션을 지키는 방향으로 수정해보면 어떨까요?

`isEmpty()` 와 같은 메서드를 예로 들 수 있습니다.
위의 경우에는 `isFirstNameExist` 와 같이 수정해주는 것이 적당해보입니다.

(*추가적으로 공식 홈페이지에 있는 컨벤션 관련 [자료 링크](https://www.swift.org/documentation/api-design-guidelines/#naming)입니다.)

2023-03-09 09:26 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/StudentManager.swift
> +        var firstNameExist = false
@keenkim1202 
수정 완료했습니다!

2023-03-10 04:44 UTC, keenkim1202 requested changes

2023-03-10 04:44 UTC, keenkim1202 commented on SnapkitPractice/SnapkitPractice/StudentManager.swift
> +        var firstNameExist = false
@DONOTINTO 
함수 명이 아니라 이 변수의 이름 수정을 의미한 것입니다!
```swift
var firstNameExist = false // <- here
```
위의 함수의 경우는 리턴 타입이 없기 때문에 해당 이름이 적절하지 않습니다!

2023-03-10 06:58 UTC, DONOTINTO commented on SnapkitPractice/SnapkitPractice/StudentManager.swift
> +        var firstNameExist = false
@keenkim1202 수정했습니다!

2023-03-13 05:09 UTC, keenkim1202 approved these changes

2023-03-13 05:13 UTC, merged