Address book
DONOTINTO/IOSProjects pull request #9
Opened 2023-03-15 15:06 UTC by DONOTINTO

2023-03-16 07:17 UTC, keenkim1202 requested changes
충분히 잘 작성한 부분도 많습니다😊
힘내서 수정해보세요~!
@DONOTINTO

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +        var isFavorite  = false
변수 이름 좋습니다! 👍🏻

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +
비워둔 함수에는 항상 향후 작성할 내용에 대해 코멘트를 남겨주세요!
```suggestion
        // TODO: 이미지 추가 기능 구현 예정
```

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +
코멘트가 없는 경우는 
- 함수를 잘못 작성하였는지
- 사용하지 않은 함수인지
- 미래에 구현 예정이라 비워둔것인지
- 현재 구현하다 막힌 것인지
등을 파악할 수 없습니다.
현재 어떤 상태인지 명시해주시면 됩니다.

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +        yesButton.setBackgroundColor(button: yesButton, isSelected: yesButton.isSelected )
```suggestion
        yesButton.setBackgroundColor(button: yesButton, isSelected: yesButton.isSelected)
```
뒤에 불필요한 공백 지워주세요!

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +        noButton.isSelected.toggle()
TIP: `yesButtonClicked()`와 `noButtonClicked()` 함수의 기능이 똑같다면 
공통사항을 함수로 빼면 가독성을 올릴 수 있습니다.

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +        noButton.isSelected.toggle()
(필수는 아니니 필요시 함수로 빼보세요~!)

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +        nameTextField.leftView  = UIView(frame: CGRect(x: 0.0, y: 0.0, width: 8.0, height: 0))
```suggestion
        nameTextField.leftView  = UIView(frame: CGRect(x: 0, y: 0, width: 8, height: 0))
```

소수점 자리가 `0`으로 떨어지는 경우는 `.0`을 생략하여 표기합니다.

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/DetailViewController.swift
> +            $0.trailing.equalTo(view.safeAreaLayoutGuide.snp.trailing).offset(-10)
```suggestion
            $0.trailing.equalTo(view.snp.trailing).offset(-10)
```

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/MemberTableViewCell.swift
> +        if isFavorite {
위에 한 줄 띄워주세요!
(convention: if문 앞에 한줄띄기)

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/MemberTableViewCell.swift
> +        // let memberImage = MemberManger.shared.memberImage(index: index)
혹시 사용하지 않는 주석인 경우는 삭제, 
향후 사용예정의 코드의 경우는 위에 명시해주세요.
```suggestion
       // TODO: 향후 000 구현할 때 사용 예정.
        // let memberImage = MemberManger.shared.memberImage(index: index)
```

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/UIKitExtension.swift
> +        guard let string = self.placeholder else {
return 문이 짧을 경우 (짧은 단어 하나, 프로퍼티 하나 정도?) 한 줄로 작성해주세요!

```suggestion
        guard let string = self.placeholder else { return }
```

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/ViewController.swift
> +    func reloadTable() {
```suggestion
    func reloadTableView() {
```

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/ViewController.swift
> +        //초기 설정
위의 다른 파일들과 일관성있게
`initalSetup()` 함수 안에 넣어주세요

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/ViewController.swift
> +        if allCategoryButton.isSelected {
위에 한 줄 띄어주세요 (convension)

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/ViewController.swift
> +        if allCategoryButton.isSelected {
위에 한 줄 띄어주세요 (convension)

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/ViewController.swift
> +class ViewController: UIViewController, NotifyViewDiss {
`NotifyViewDiss` 의 명칭이 너무 모호합니다.
이름을 수정해보세요!

2023-03-16 07:17 UTC, keenkim1202 commented on AddressBook_/AddressBook_/ViewController.swift
> +class ViewController: UIViewController, NotifyViewDiss {
너무 긴 이름도 좋지 않지만, 너무 줄인 명칭도 좋지 않습니다!
조금 길더라도 나 아닌 다른 협업자도 알아볼 수 있도록 작성하는 것이 좋습니다.

2023-03-20 04:35 UTC, keenkim1202 requested changes
@DONOTINTO 이전 코멘트들 중 수정사항이 반영된게 있다면 답글 달아주세요!
지금 확인해봤을 때는 수정된 사항이 없는듯해보입니다.

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +    func reloadTable() {
@DONOTINTO 함수는 하단으로 이동해주세요~!

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        mainTableView.register(MemberTableViewCell.self , forCellReuseIdentifier: "MemberCell")
```suggestion
        mainTableView.register(MemberTableViewCell.self, forCellReuseIdentifier: "MemberCell")
```

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        //초기 설정
초기 설정 코드는 함수를 만들어 분리해주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +//            $0.trailing.equalTo(testButton.snp.leading).offset(-10)
사용하지 않는 코드라면 지워주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        if allCategoryButton.isSelected {
if문 위에 한 줄 띄워주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        if allCategoryButton.isSelected {
if문 위에 한 줄 띄워주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +    @objc func testButtonClicked() {
내부 코드가 비어있는 함수의 경우 아래와 같이 작성해주세요
```suggestion
    @objc func testButtonClicked() { }
```

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        func getIndex(index: Int) {
함수 위에 한 줄 띄우고, 함수 내부 코드가 비어있다면 한 줄로 표기해주세요.
그리고 향후 사용할 코드라면 내부 코드를 작성하지 않은 이유를 코멘트 남겨주세요!

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Model/memberManager.swift
> +
불필요한 공백은 제거 해ㅜㅈ세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/UIKitExtension.swift
> +//  UIKitExtension.swift
파일 이름을 수정헤주세요!

extension은 각각 파일을 분리해서 작성해주어야 합니다.

- `UIViewController+.swift`
- `UITextField+.swift`
- ...

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/UIKitExtension.swift
> +extension DetailViewController: UITextFieldDelegate {
마찬가지로 내부코드가 비어있는 경우 한 줄로 작성해주세요.

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/UIKitExtension.swift
> +extension DetailViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {
`UIImagePickerControllerDelegate`, `UINavigationControllerDelegate` 둘은 완전 다른 프로토콜입니다.
분리하여 작성해주세요~

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/DetailViewController.swift
> +              let memo  = memoTextView.text else {
```suggestion
              let memo  = memoTextView.text else { return }
```

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/DetailViewController.swift
> +
불필요한 빈 줄은 제거해주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/DetailViewController.swift
> +        }
함수가 끝나고 아래 한줄을 띄워주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/DetailViewController.swift
> +        let alertCancelAction = UIAlertAction(title: "취소", style: .cancel)
위에 한 줄 띄어주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/DetailViewController.swift
> +            let stringInText = text.filter {
filter문 안의 조건이 짧은 경우 한 줄로 작성해주세요.
```suggestion
            let stringInText = text.filter { !$0.isNumber }
```

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/DetailViewController.swift
> +        return true
리턴문 앞에 한 줄 띄어주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        if allCategoryButton.isSelected {
extension에 `setBackgroundColor()` 를 만들어두셨으니 그걸 활용해보세요~

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/Controller/ViewController.swift
> +        if allCategoryButton.isSelected {
extension에 `setBackgroundColor()` 를 만들어두셨으니 그걸 활용해보세요~

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/View/MemberTableViewCell.swift
> +
불필요한 빈 줄은 지워주세요

2023-03-20 04:35 UTC, keenkim1202 commented on AddressBook_/AddressBook_/View/MemberTableViewCell.swift
> +        if isFavorite {
if문 앞에 한 줄 띄어주세요

2023-03-20 04:37 UTC, keenkim1202 commented
@DONOTINTO 꼭 수정 먼저 모두 진행된 후 새로운 기능을 구현하시길 바랍니다!

2023-03-20 06:04 UTC, DONOTINTO commented on AddressBook_/AddressBook_/View/MemberTableViewCell.swift
> +        if isFavorite {
@keenkim1202 전부 수정 완료했습니다!

2023-03-20 06:05 UTC, DONOTINTO commented on AddressBook_/AddressBook_/DetailViewController.swift
> +        noButton.isSelected.toggle()
@keenkim1202 이 부분은 어떻게 하면 더 좋을지 모르겠습니다..!

2023-03-20 06:51 UTC, keenkim1202 approved these changes

2023-03-20 06:51 UTC, merged